"$schema" = 'https://starship.rs/config-schema.json'

format = """
${custom.recent_dir_parent}${custom.recent_dir_base}   ${custom.recent_file_parent}${custom.recent_file_base}

[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$python\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[bun]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = " "
style = "bg:#212736 fg:#769ff0"
# Đưa trực tiếp biến $virtualenv vào chuỗi format
format = '[[ $symbol ($version) ($virtualenv) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
# Định nghĩa ký tự hiển thị ở cuối thanh prompt
success_symbol = "[❯](bold #50FA7B)"
error_symbol = "[❯](bold #FF5555)"

# =========================================
# MODULE THƯ MỤC RECENT
# =========================================
[custom.recent_dir_parent]
# Dùng dirname để lấy đường dẫn cha, sed để đổi $HOME thành ~
command = 'tail -n 1 ~/.cache/dir_recent.log | grep -o "/.*" | xargs dirname | sed "s|^$HOME|~|"'
when = 'test -s ~/.cache/dir_recent.log'
# In ra màu xám mờ (#6272a4) kèm icon, nối thêm dấu / ở cuối
format = ' [ $output/](fg:#6272a4)'

[custom.recent_dir_base]
# Dùng basename để chỉ lấy tên thư mục cuối cùng
command = 'tail -n 1 ~/.cache/dir_recent.log | grep -o "/.*" | xargs basename'
when = 'test -s ~/.cache/dir_recent.log'
# In ra màu hồng nổi bật, chữ in nghiêng và đậm
format = '[$output](fg:#ff79c6 bold italic)'

# =========================================
# MODULE FILE RECENT
# =========================================
[custom.recent_file_parent]
command = 'sort -rn ~/.cache/nvim_recent.log | head -n 1 | grep -o "/.*" | xargs dirname | sed "s|^$HOME|~|"'
when = 'test -s ~/.cache/nvim_recent.log'
# In ra màu xám mờ (#6272a4) kèm icon, nối thêm dấu / ở cuối
format = '[󰈔 $output/](fg:#6272a4)'

[custom.recent_file_base]
command = 'sort -rn ~/.cache/nvim_recent.log | head -n 1 | grep -o "/.*" | xargs basename'
when = 'test -s ~/.cache/nvim_recent.log'
# In ra màu vàng rực, chữ in nghiêng và đậm
format = '[$output](fg:#f1fa8c bold italic) '
