loop-playlist=inf
# Bật tính năng bộ nhớ đệm (thường tự bật cho stream mạng, nhưng cứ ép bật cho chắc)
cache=yes

# Dung lượng RAM tối đa để lưu phần tải trước (ví dụ: 1024M = 1GB)
demuxer-max-bytes=1024M

# Dung lượng RAM tối đa để LƯU GIỮ phần ĐÃ XEM (Cực kỳ quan trọng cho vòng lặp)
# Đặt bằng với demuxer-max-bytes để nguyên file nằm gọn trong RAM
demuxer-max-back-bytes=1024M
